const fs = require('fs');

let content = fs.readFileSync('frontend/src/translations/translations.js', 'utf8');

// Replace ti minimal with full
const tiPattern = /ti:\s*\{[^}]+mainCampus:[^\n]+\n\s*\},/s;
const tiFull = `ti: {
    home: "ገጽ",
    dormitoryView: "ናይ መደቀሲ ቤት ትርኢት",
    applicationForm: "ናይ መመልከቲ ቅጥዒ",
    reportIssue: "ጸገም ሪፖርት ግበር",
    studentService: "ናይ ተምሃሮ ኣገልግሎት",
    universityName: "ዩኒቨርሲቲ ኦዳ ቡልቱም",
    universityMotto: "ትምህርቲ ንምዕባለ ሕብረተሰብ",
    welcomeMessage: "ናብ ኦቢዩ ናይ ተምሃሮ ኣገልግሎት እንቋዕ ብደሓን መጻእኩም",
    exploreCampus: "ካምፓስ ምርምር",
    findDormPlacement: "ናይ መደቀሲ ቤትካ ቦታ ርኸብ",
    enterUniversityId: "ናይ ዩኒቨርሲቲ መለለዪኻ ኣእቱ",
    universityId: "ናይ ዩኒቨርሲቲ መለለዪ",
    viewPlacement: "ቦታ ርአ",
    searching: "ይድለ ኣሎ...",
    dormitoryPlacementDetails: "ዝርዝር ናይ መደቀሲ ቤት ቦታ",
    yourRoom: "ክፍልኻ",
    fullName: "ምሉእ ስም",
    sex: "ጾታ",
    department: "ክፍሊ",
    building: "ህንጻ",
    roomNumber: "ቁጽሪ ክፍሊ",
    campus: "ካምፓስ",
    capacity: "ዓቕሚ",
    students: "ተምሃሮ",
    print: "ሕትመት",
    savePdf: "PDF ዓቅብ",
    newSearch: "ሓድሽ ምድላይ",
    dormitoryApplicationForm: "ናይ መደቀሲ ቤት መመልከቲ ቅጥዒ",
    completeAllSections: "ኩሎም ክፋላት ብትኽክል ምላእ",
    personal: "ውልቃዊ",
    educational: "ትምህርታዊ",
    school: "ቤት ትምህርቲ",
    family: "ስድራቤት",
    emergency: "ህጹጽ",
    agreement: "ስምምዕ",
    help: "ሓገዝ",
    saveAndContinue: "ዓቅብን ቀጽልን",
    saving: "ይዕቀብ ኣሎ...",
    submitApplication: "መመልከቲ ኣቕርብ",
    submittingApplication: "መመልከቲ ይቐርብ ኣሎ...",
    name: "ስም",
    fatherName: "ስም ኣቦ",
    gFatherName: "ስም ኣያት",
    gender: "ጾታ",
    male: "ተባዕታይ",
    female: "ኣንስተይቲ",
    reportFacilityIssue: "ጸገም ትካል ሪፖርት ግበር",
    letUsKnowProblems: "ኣብ መደቀሲ ቤትካ ዘሎ ዝኾነ ጸገም ንገረና",
    block: "ብሎክ",
    description: "መግለጺ",
    describeIssue: "ጸገም ግለጽ...",
    clear: "ጽርግያ",
    submitReport: "ሪፖርት ኣቕርብ",
    submitting: "ይቐርብ ኣሎ...",
    success: "ዓወት!",
    error: "ጌጋ",
    loading: "ይጽዕን ኣሎ...",
    mainCampus: "ቀንዲ ካምፓስ"
  },`;

content = content.replace(tiPattern, tiFull);

// Replace ar minimal with full
const arPattern = /ar:\s*\{[^}]+mainCampus:[^\n]+\n\s*\}/s;
const arFull = `ar: {
    home: "الرئيسية",
    dormitoryView: "عرض السكن",
    applicationForm: "نموذج التقديم",
    reportIssue: "الإبلاغ عن مشكلة",
    studentService: "خدمة الطلاب",
    universityName: "جامعة أودا بولتوم",
    universityMotto: "التعليم من أجل تنمية المجتمع",
    welcomeMessage: "مرحباً بكم في خدمات طلاب جامعة أودا بولتوم",
    exploreCampus: "استكشف الحرم الجامعي",
    findDormPlacement: "ابحث عن موقع سكنك",
    enterUniversityId: "أدخل رقم هويتك الجامعية لعرض السكن المخصص لك",
    universityId: "الهوية الجامعية",
    viewPlacement: "عرض الموقع",
    searching: "جاري البحث...",
    dormitoryPlacementDetails: "تفاصيل موقع السكن",
    yourRoom: "غرفتك",
    fullName: "الاسم الكامل",
    sex: "الجنس",
    department: "القسم",
    building: "المبنى",
    roomNumber: "رقم الغرفة",
    campus: "الحرم الجامعي",
    capacity: "السعة",
    students: "الطلاب",
    print: "طباعة",
    savePdf: "حفظ PDF",
    newSearch: "بحث جديد",
    dormitoryApplicationForm: "نموذج طلب السكن",
    completeAllSections: "أكمل جميع الأقسام بدقة",
    personal: "شخصي",
    educational: "تعليمي",
    school: "المدرسة",
    family: "العائلة",
    emergency: "طوارئ",
    agreement: "اتفاقية",
    help: "مساعدة",
    saveAndContinue: "حفظ ومتابعة",
    saving: "جاري الحفظ...",
    submitApplication: "تقديم الطلب",
    submittingApplication: "جاري تقديم الطلب...",
    name: "الاسم",
    fatherName: "اسم الأب",
    gFatherName: "اسم الجد",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    reportFacilityIssue: "الإبلاغ عن مشكلة في المرافق",
    letUsKnowProblems: "أخبرنا عن أي مشاكل في سكنك",
    block: "المبنى",
    description: "الوصف",
    describeIssue: "صف المشكلة...",
    clear: "مسح",
    submitReport: "إرسال التقرير",
    submitting: "جاري الإرسال...",
    success: "نجح!",
    error: "خطأ",
    loading: "جاري التحميل...",
    mainCampus: "الحرم الرئيسي"
  }`;

content = content.replace(arPattern, arFull);

fs.writeFileSync('frontend/src/translations/translations.js', content);
console.log('✅ Added complete Tigrinya and Arabic translations!');
